#!/bin/bash

builddir=${builddir:-.}
#echo $USERNAME : $REASON : $DEVICE

verify_env_set() {
	if test -z "${!1}";then
		echo "$1 environment variable was not set" >&2
		exit 1
	fi
}

# Verify the common environment variables
verify_env_set "IP_REMOTE"
verify_env_set "REASON"
verify_env_set "HOSTNAME"
verify_env_set "REMOTE_HOSTNAME"
verify_env_set "USERNAME"
verify_env_set "USER_AGENT"
verify_env_set "DEVICE_PLATFORM"
verify_env_set "DEVICE_TYPE"

# VPNNET_BASE is exported by the test (test-pass-script) to ocserv
case "$REASON" in
  connect)
	verify_env_set "DEVICE"

	test "${OCSERV_DNS}" = "${VPNNET_BASE}.1 203.0.113.1 " && \
	test "${OCSERV_DNS4}" = "${VPNNET_BASE}.1 203.0.113.1 " && \
	test "${OCSERV_ROUTES}" = "${VPNNET_BASE}.0/255.255.255.0 203.0.113.0/255.255.255.0 " && \
	test "${OCSERV_ROUTES4}" = "${VPNNET_BASE}.0/255.255.255.0 203.0.113.0/255.255.255.0 " && \
	echo "${IP_REMOTE}" > ${builddir}/connect.ok
	;;
  disconnect)
	if ! test -z "$DEVICE";then
		test "${OCSERV_DNS}" = "${VPNNET_BASE}.1 203.0.113.1 " && \
		test "${OCSERV_DNS4}" = "${VPNNET_BASE}.1 203.0.113.1 " && \
		test "${OCSERV_ROUTES}" = "${VPNNET_BASE}.0/255.255.255.0 203.0.113.0/255.255.255.0 " && \
		test "${OCSERV_ROUTES4}" = "${VPNNET_BASE}.0/255.255.255.0 203.0.113.0/255.255.255.0 " && \
		echo "${IP_REMOTE}" > ${builddir}/disconnect.ok
	fi
	;;
  "host-update")
	verify_env_set "HOSTNAME"
	echo > ${builddir}/host-update.ok
	;;
esac

exit 0
