#!/bin/bash
#
# Copyright (C) 2016 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
NO_NEED_ROOT=1

VERBOSE=1

. `dirname $0`/common.sh

eval "${GETPORT}"

echo "Testing PAM backend with username-password... "

export TEST_PAMDIR=data/pam
update_config test-pam.config
launch_sr_pam_server -d 1 -f -c ${CONFIG} & PID=$!
wait_server $PID

echo ""
echo "Connecting with wrong password... "
( echo -e "testuser\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v $ADDRESS:$PORT --authgroup group2 -u testuser --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
	fail $PID "Received cookie with wrong cred"

echo ""
echo "Connecting with empty password... "
( echo -e "\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v $ADDRESS:$PORT --authgroup group2 -u testuser --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
	fail $PID "Received cookie with wrong cred"

echo ""
echo "Connecting with wrong username... "
( echo -e "testuser123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v $ADDRESS:$PORT --authgroup group2 -u test --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
	fail $PID "Received cookie with wrong cred"

echo ""
echo "Connecting with correct password... "
( echo -e "testuser123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v $ADDRESS:$PORT --authgroup group2 -u testuser --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly ) ||#>/dev/null 2>&1 ) ||
	fail $PID "Could not receive cookie from server"


echo ""
echo "Verify that vhost2 credentials are rejected on vhost1..."
( echo -e "vhost2user123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost1.example.com:${PORT} --resolve vhost1.example.com:${ADDRESS} --authgroup group2 -u vhost2user --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
        fail $PID "Unauthorized user from vhost2 was able to authenticate to vhost1"

echo ""
echo "Verify that valid vhost1 credentials are accepted..."
( echo -e "vhost1user123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost1.example.com:${PORT} --resolve vhost1.example.com:${ADDRESS} --authgroup group2 -u vhost1user --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) ||
        fail $PID "Valid user was unable to authenticate to vhost1"

echo ""
echo "Verify that vhost1 credentials are rejected on vhost2..."
( echo -e "vhost1user123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost2.example.com:${PORT} --resolve vhost2.example.com:${ADDRESS} --authgroup group2 -u vhost1user --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
        fail $PID "Unauthorized user from vhost1 was able to authenticate to vhost2"

echo ""
echo "Verify that valid vhost2 credentials are accepted..."
( echo -e "vhost2user123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost2.example.com:${PORT} --resolve vhost2.example.com:${ADDRESS} --authgroup group2 -u vhost2user --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) ||
        fail $PID "Valid user was unable to authenticate to vhost2"

echo ""
echo "Verify invalid credentials are rejected on vhost3 (minimal PAM options)..."
( echo -e "testtest\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost3.example.com:${PORT} --resolve vhost3.example.com:${ADDRESS} --authgroup group2 -u testuser --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) &&
        fail $PID "vhost3 (minimal PAM) accepted invalid credentials"

echo ""
echo "Verify valid credentials are accepted on vhost3 (minimal PAM options)..."
( echo -e "testuser123\n" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -v vhost3.example.com:${PORT} --resolve vhost3.example.com:${ADDRESS} --authgroup group2 -u testuser --servercert=pin-sha256:xp3scfzy3rOQsv9NcOve/8YVVv+pHr4qNCXEXrNl5s8= --cookieonly >/dev/null 2>&1 ) ||
        fail $PID "vhost3 (minimal PAM) rejected valid credentials"

cleanup

exit 0
